{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  labels:
    {{- include "hyperv-csi.labels" $ | nindent 4 }}
  {{- if or .isDefault .annotations }}
  annotations:
    {{- if .isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
provisioner: {{ include "hyperv-csi.driverName" $ }}
reclaimPolicy: {{ dig "reclaimPolicy" "Retain" . }}
volumeBindingMode: {{ dig "volumeBindingMode" "Immediate" . }}
allowVolumeExpansion: {{ dig "allowVolumeExpansion" true . }}
{{- with .parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
