using System.Security.Cryptography.X509Certificates;
using HyperVCsiAgent.Core.Security;

namespace HyperVCsiAgent.Core.Configuration;

/// <summary>
/// How the agent finds its HTTPS server certificate and which callers it
/// answers as. The certificate is self-signed, generated by hand the same way
/// the driver's client certificate is - there is no CA and nothing rotates on
/// its own - so it is selected from the store by pinning
/// <see cref="AllowedThumbprints"/>, the mirror image of how the agent itself
/// pins the driver's client certificate.
/// </summary>
public sealed class TlsOptions
{
    /// <summary>
    /// SHA-1 thumbprints of the server certificates this agent is willing to
    /// serve from the store. Ordinarily just the one currently in use; two
    /// during a rotation - install the new certificate, add its thumbprint
    /// here, wait for <see cref="ReloadInterval"/> to pick it up, then remove
    /// the old one. Empty means TLS is not configured, which is only allowed
    /// in Development - see <see cref="IsConfigured"/>.
    /// </summary>
    public string[] AllowedThumbprints { get; set; } = [];

    public string StoreName { get; set; } = "My";

    public string StoreLocation { get; set; } = "LocalMachine";

    /// <summary>
    /// How often to re-read the certificate store. A certificate swapped in by
    /// an operator - as part of a manual rotation - is picked up on the next
    /// connection after this elapses, without the clustered role being
    /// restarted.
    /// </summary>
    public TimeSpan ReloadInterval { get; set; } = TimeSpan.FromHours(1);

    public int Port { get; set; } = 443;

    /// <summary>
    /// Unlike a subject-name match, nothing but this list identifies which
    /// store certificate is the right one to serve - so having at least one
    /// entry is what "TLS is configured" means, with nothing else needed to
    /// decide it.
    /// </summary>
    public bool IsConfigured => AllowedThumbprints.Length > 0;

    /// <summary>
    /// Parsed store identity. Parsing here rather than at the point of use
    /// means a typo fails the role at startup - loudly, where the cluster
    /// reports it - instead of throwing inside every TLS handshake while the
    /// service still reports itself Online.
    /// </summary>
    public (StoreName Name, StoreLocation Location) ResolveStore()
    {
        if (!Enum.TryParse<StoreName>(StoreName, ignoreCase: true, out var name))
        {
            throw new InvalidOperationException(
                $"{AgentOptions.SectionName}:Tls:{nameof(StoreName)} '{StoreName}' is not a certificate store name; " +
                $"expected one of {string.Join(", ", Enum.GetNames<StoreName>())}");
        }

        if (!Enum.TryParse<StoreLocation>(StoreLocation, ignoreCase: true, out var location))
        {
            throw new InvalidOperationException(
                $"{AgentOptions.SectionName}:Tls:{nameof(StoreLocation)} '{StoreLocation}' is not a certificate store location; " +
                $"expected one of {string.Join(", ", Enum.GetNames<StoreLocation>())}");
        }

        return (name, location);
    }

    public void Validate()
    {
        if (!IsConfigured)
        {
            return;
        }

        ResolveStore();

        if (ReloadInterval <= TimeSpan.Zero)
        {
            throw new InvalidOperationException(
                $"{AgentOptions.SectionName}:Tls:{nameof(ReloadInterval)} must be positive");
        }

        if (Port is < 1 or > 65535)
        {
            throw new InvalidOperationException(
                $"{AgentOptions.SectionName}:Tls:{nameof(Port)} must be a valid port number");
        }

        // No "AllowedThumbprints is empty" check here: IsConfigured (which
        // gates entry to this method) already means AllowedThumbprints is
        // non-empty - there is no longer a distinct "configured but no
        // thumbprints" state to reject.
        foreach (var thumbprint in AllowedThumbprints)
        {
            var normalized = ClientCertificateAuthenticator.Normalize(thumbprint);
            if (ClientCertificateAuthenticator.IsWellFormed(normalized))
            {
                continue;
            }

            throw new InvalidOperationException(
                $"{AgentOptions.SectionName}:Tls:{nameof(AllowedThumbprints)} entry '{thumbprint}' is not a SHA-1 thumbprint: " +
                $"expected {ClientCertificateAuthenticator.ThumbprintLength} hex characters, got {normalized.Length}. " +
                "Paste only the fingerprint, without any label.");
        }
    }
}
